# GitHub Actions Workflow for Running Python Tests

name: Python CI  # Name of the workflow

on: [push, pull_request]  # Trigger on push and pull request events

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out your code

      - name: Set up Python
        uses: actions/setup-python@v4  # Installs Python
        with:
          python-version: "3.x"  # Uses the latest Python 3 version

      - name: Install dependencies
        run: pip install pytest  # Install pytest

      - name: Run tests
        run: pytest test_script.py  # Execute the test file
